engines:
  pep8:
    enabled: true
  fixme:
    enabled: true
  radon:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - python:
ratings:
   paths:
   - "**/*.py"
exclude_paths:
- "**/tests.py"
- "tests/**/*"
- "docs/**/*"
