language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

matrix:
  allow_failures:
    - python: "3.7-dev"

before_script:
  - pip install pipenv
  - pipenv install --system -d

script:
  - pipenv run python setup.py test
